spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    password: mysecretpassword
    url: jdbc:postgresql://postgres_container:5432/postgres
    username: postgres
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
